---
- name: Ensure GitLab prerequisites are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ gitlab_server_prerequisites }}"

- name: Ensure GitLab is installed
  ansible.builtin.package:
    name: gitlab-ee

- name: Ensure the GitLab configuration is present
  ansible.builtin.template:
    src: etc/gitlab/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: "0600"
  notify: Reconfigure GitLab
