---
gitlab_server_external_url: http://git.example.com
gitlab_server_default_theme: 2

# Nginx base configuration
gitlab_server_nginx_redirect_http_to_https: false
gitlab_server_nginx_listen_addresses:
  - "*"
  - "[::]"
gitlab_server_nginx_listen_port: 80
gitlab_server_nginx_listen_https: false
# gitlab_server_nginx_real_ip_trusted_addresses: []
# gitlab_server_nginx_real_ip_header: 'X-Forwarded-For'
# gitlab_server_nginx_real_ip_recursive: True
