---
namespace: dubzland
name: gitlab
version: "1.1.1"
readme: README.md
authors:
  - Josh Williams <jdubz@dubzland.com>
description: Installs and configures the GitLab DevOps server.
license_file: COPYING
tags:
  - linux
  - debian
  - ubuntu
  - gitlab
  - devops

dependencies:
  community.general: "*"

repository: https://git.dubzland.com/dubzland/ansible-collections/gitlab

# The URL to any online docs
documentation: |
  https://docs.dubzland.io/ansible-collections/collections/dubzland/gitlab/

# The URL to the homepage of the collection/project
homepage: https://git.dubzland.com/dubzland/ansible-collections/gitlab

# The URL to the collection issue tracker
issues: https://git.dubzland.com/dubzland/ansible-collections/gitlab/-/issues
build_ignore:
  - .ansible-lint
  - .cache
  - .gitignore
  - .gitlab-ci.yml
  - .venv
  - .yamllint
  - requirements-*.txt
  - extensions
