---
argument_specs:
  main:
    short_description: |
      Installs and configures the L(GitLab,https://gitlab.com) DevOps server.
    description:
      - Sets up the GitLab apt repository
      - Installs the gitlab-ee package
      - Creates and applies the GitLab configuration
    options:
      gitlab_server_default_theme:
        type: int
        default: 2
        description: Default theme for the GitLab web UI.
      gitlab_server_puma_worker_processes:
        type: int
        description: |-
          Number of Puma workers to run.  Set to 0 to disable Puma clustered
          mode.  See L(https://docs.gitlab.com/ee/administration/operations/puma.html#disable-puma-clustered-mode-in-memory-constrained-environments)
          for more information.  Generally speaking, this setting should not be
          used.  Primarily exists for reducing resource usage during CI runs.
      gitlab_server_nginx_client_max_body_size:
        type: str
        default: 250m
        description: Maximum payload size allowed by Nginx.
      gitlab_server_nginx_redirect_http_to_https:
        type: bool
        default: true
        description: Should http requests to the server be redirected to https.
      gitlab_server_nginx_listen_addresses:
        type: list
        elements: str
        default:
          - "*"
          - "[::]"
        description: Local addresses the GitLab Nginx server should bind to.
      gitlab_server_nginx_listen_port:
        type: int
        description: If present, specifies the port Nginx should listen on.
      gitlab_server_nginx_listen_https:
        type: bool
        description: |
          Listen on https (443).  Set to V(False) if using a reverse proxy.
      gitlab_server_nginx_real_ip_trusted_addresses:
        type: list
        elements: str
        description: List of upstream reverse proxies.
      gitlab_server_nginx_real_ip_header:
        type: str
        description: HTTP header containing upstream proxy addresses.
      gitlab_server_nginx_real_ip_recursive:
        type: bool
        description: Enable Nginx Real-Ip recursive search.
      gitlab_server_smtp_enable:
        type: bool
        description: >-
          Enables sending email via an external server, as opposed to using
          Sendmail or Postfix directly.
      gitlab_server_smtp_address:
        type: str
        description: >-
          Address of the SMTP server used for sending emails.
      gitlab_server_smtp_port:
        type: int
        description: Port the O(gitlab_server_smtp_address) is listening on.
      gitlab_server_smtp_user_name:
        type: str
        description: Username used to authenticate to the SMTP server.
      gitlab_server_smtp_password:
        type: str
        description: Password that corresponds to O(gitlab_server_smtp_user_name).
      gitlab_server_smtp_domain:
        type: str
        description: Domain to authenticate to.
      gitlab_server_smtp_authentication:
        type: str
        choices:
          - login
          - plain
        description: Authentication method to use with the SMTP server.
      gitlab_server_smtp_enable_starttls_auto:
        type: bool
        description: Use STARTTLS on the SMTP server if present.
      gitlab_server_smtp_tls:
        type: bool
        description: Enables TLS authentication with the SMTP server.
      gitlab_server_smtp_pool:
        type: bool
        description: Enables SMTP connection pooling.
      gitlab_server_smtp_openssl_verify_mode:
        type: str
        choices:
          - none
          - peer
          - client_once
          - fail_if_no_peer_cert
        description: >-
          Sets how OpenSSL checks the certificate.  See
          L(ActionMailer,https://api.rubyonrails.org/classes/ActionMailer/Base.html)
          for more information.
      gitlab_server_smtp_ca_path:
        type: path
        description: Path to the CA to use for validating peer cerficates.
      gitlab_server_smtp_ca_file:
        type: path
        description: Actual CA certificate.
      gitlab_server_email_enabled:
        type: bool
        description: Enables email originating from the GitLab server.
      gitlab_server_email_from:
        type: str
        description: Email address listed as the sender on outbound emails.
      gitlab_server_email_display_name:
        type: str
        description: Name displayed as the sender on outbound emails.
      gitlab_server_email_reply_to:
        type: str
        description: Reply-to address for outbound emails.
      gitlab_server_pages_enable:
        type: bool
        default: false
        description: Enable GitLab Pages functionality.
      gitlab_server_pages_external_url:
        type: str
        description: Base URL under which GitLab will server Pages projects.
      gitlab_server_pages_external_http:
        type: list
        elements: str
        description: |-
          List of IP addresses the Pages daemon will bind to (for http).
          Necessary if you want to use custom domains. See
          L(https://docs.gitlab.com/ee/administration/pages/index.html#advanced-configuration)
          for more information.
      gitlab_server_pages_external_https:
        type: list
        elements: str
        description: |-
          List of IP addresses the Pages daemon will bind to (for https).
          Necessary if you want to use custom domains. See
          L(https://docs.gitlab.com/ee/administration/pages/index.html#advanced-configuration)
          for more information.
      gitlab_server_pages_nginx_enable:
        type: bool
        description: |-
          Controls the GitLab Pages Nginx instance.  If you are planning on
          utilizing custom domains, this should be disabled.  See
          L(https://docs.gitlab.com/ee/administration/pages/index.html#advanced-configuration)
          for more information.
      gitlab_server_pages_redirect_http:
        type: bool
        description: Redirect Pages traffic from HTTP to HTTPS
      gitlab_server_pages_cert:
        type: path
        description: Certificate file used by the GitLab Pages server.
      gitlab_server_pages_cert_key:
        type: path
        description: Certificate key file used by the GitLab Pages server.
      gitlab_server_pages_access_control:
        type: bool
        description: |-
          Enables
          L(Access control,https://docs.gitlab.com/ee/administration/pages/#access-control)
          for the Pages daemon.
      gitlab_server_object_store_enabled:
        type: bool
        description: Enables the consoldated configuration for Object Storage.
      gitlab_server_object_store_connection:
        type: dict
        options:
          provider:
            type: str
            choices:
              - AWS
              - Google
              - AzureRM
          region:
            type: str
            description: AWS Region (us-east-1 for Minio)
          endpoint:
            type: str
            description: >-
              Can be used to configure an S3 compatible service (like Minio).
          aws_access_key_id:
            type: str
            description: AWS credentials.
          aws_secret_access_key:
            type: str
            description: AWS credentials.
          path_style:
            type: bool
            description: Set to V(true) if using Minio, otherwise V(false).
        description: >-
          Connection configuration for the object store.  See
          L(https://docs.gitlab.com/ee/administration/object_storage.html)
          for details.
      gitlab_server_object_store_proxy_download:
        type: bool
        description: Proxy all object requests through the GitLab server.
      gitlab_server_object_store_bucket_artifacts:
        type: str
        description: Name of the bucket used for artifact storage.
      gitlab_server_object_store_bucket_external_diffs:
        type: str
        description: Name of the bucket used for merge request diffs.
      gitlab_server_object_store_bucket_lfs:
        type: str
        description: Name of the bucket used for Large File Storage.
      gitlab_server_object_store_bucket_uploads:
        type: str
        description: Name of the bucket used for uploads.
      gitlab_server_object_store_bucket_packages:
        type: str
        description: Name of the bucket used for project packages.
      gitlab_server_object_store_bucket_dependency_proxy:
        type: str
        description: Name of the bucket used for dependency proxy caching.
      gitlab_server_object_store_bucket_terraform_state:
        type: str
        description: Name of the bucket used for storing Terraform state.
      gitlab_server_object_store_bucket_ci_secure_files:
        type: str
        description: >-
          Name of the bucket used for storing secured files used during CI
          runs.  See L(https://docs.gitlab.com/ee/administration/secure_files.html)
          for details.
      gitlab_server_object_store_bucket_pages:
        type: str
        description: Name of the bucket used for storing Gitlab Pages.
      gitlab_server_manage_backup_path:
        type: bool
        description: >-
          Should GitLab manage the permissions and ownership of the directory
          specified in O(gitlab_server_backup_path)?
      gitlab_server_backup_path:
        type: path
        description: Directory on the GitLab server to hold backup data.
      gitlab_server_backup_keep_time:
        type: int
        description: Amount of time (in seconds) to keep old backup files.
      gitlab_server_registry_enabled:
        type: bool
        description: Enables the GitLab Container Registry.
      gitlab_server_registry_external_url:
        type: str
        description: URL under which the Container Registry is available.
      gitlab_server_registry_host:
        type: str
        description: Host running the Docker registry daemon.
      gitlab_server_registry_port:
        type: int
        description: Port the O(gitlab_server_registry_host) is listening on.
      gitlab_server_registry_path:
        type: path
        description: Directory on the GitLab server where registry data should be stored.
      gitlab_server_registry_storage:
        type: dict
        options:
          provider:
            type: str
            choices:
              - s3
          accesskey:
            type: str
            description: AWS credentials.
          secretkey:
            type: str
            description: AWS credentials.
          bucket:
            type: str
            description: Name of the bucket used to store container image data.
          region:
            type: str
            description: AWS Region (us-east-1 for Minio)
          regionendpoint:
            type: str
            description: >-
              Can be used to configure an S3 compatible service (like Minio).
          secure:
            type: bool
            description: Enables TLS encryption to the storage server.
          pathstyle:
            type: bool
            description: Set to V(true) if using Minio, otherwise V(false).
          encrypt:
            type: bool
            description: Enable server side encryption of Registry data.
          disable_redirect:
            type: bool
            description: Disables redirection of registry requests to the storage server.
        description: >-
          Connection configuration for the object store.  See
          L(https://docs.gitlab.com/ee/administration/object_storage.html)
          for details.
      gitlab_server_registry_nginx_enable:
        type: bool
        description: Enable the Nginx server for Registry access.
      gitlab_server_registry_nginx_listen_port:
        type: int
        description: Port the Registry Nginx server should listen on.
      gitlab_server_registry_nginx_listen_https:
        type: bool
        description: Enable or disable HTTPS for the Registry Nginx instance.
