---
galaxy_info:
  role_name: gitlab_server
  author: dubzland
  description: Installs and configures the GitLab DevOps server.
  license: MIT
  min_ansible_version: '2.14'

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - jammy
        - focal
        - bionic
  galaxy_tags:
    - devops
    - git
    - gitlab
    - linux
    - debian
    - ubuntu

dependencies: []
