---
gitlab_server_prerequisites:
  - cron
  - perl
  - postfix
  - tzdata
# https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/config_file.list?os=debian&dist=bookworm&source=script
gitlab_server_gpg_key_url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
gitlab_server_gpg_key_dest: >-
  /usr/share/keyrings/gitlab_gitlab-ee-archive-keyring.asc
gitlab_server_repo_url: "https://packages.gitlab.com/gitlab/gitlab-ee/\
  {{ ansible_distribution | lower }}/"
gitlab_server_repo_dest: /etc/apt/sources.list.d/gitlab_gitlab-ee.list
