---
galaxy_info:
  role_name: gitlab_runner
  author: dubzland
  description: Installs a GitLab Runner instance.
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - jammy
        - focal
        - bionic
  galaxy_tags:
    - devops
    - git
    - gitlab
    - linux
    - debian
    - ubuntu

dependencies:
  - role: dubzland.gitlab.gitlab_common
    vars:
      gitlab_common_gpg_key_url: "{{ gitlab_runner_gpg_key_url }}"
      gitlab_common_gpg_key_dest: "{{ gitlab_runner_gpg_key_dest }}"
      gitlab_common_repo_url: "{{ gitlab_runner_repo_url }}"
      gitlab_common_repo_dest: "{{ gitlab_runner_repo_dest }}"
