---
galaxy_info:
  role_name: gitlab_common
  author: dubzland
  description: Performs tasks common to both Server and Runner.
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - jammy
        - focal
        - bionic
  galaxy_tags:
    - devops
    - git
    - gitlab
    - linux
    - debian
    - ubuntu

dependencies: []
